# Generated by Django 4.2.2 on 2024-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriBackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pesticides', 'Pesticides'), ('BigPlant', 'Bigplant'), ('SmallPlant', 'Smallplant'), ('Fertilizer', 'Fertilizer')], default='Pesticides', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
